# coding: utf-8
from flask import Blueprint
from . import endpoint

__all__ = ['blueprint']

blueprint = b = Blueprint('api_v1', __name__)

# lit
# b.add_url_rule('/lip/<path:filename>', 'lip-fuck-you', endpoint.test.ack)

b.add_url_rule('/lit/test', 'lit-test', endpoint.test.test)
b.add_url_rule('/lit/hello', 'lit-hello', endpoint.test.hello)
b.add_url_rule('/lit/test_anti', 'lit-test_anti', endpoint.test.test_anti)

# sms-code
b.add_url_rule('/lit/get_sms_code', 'get-sms-code', endpoint.sms_code.get_sms_code, methods=['POST'])

# user
b.add_url_rule('/lit/user/phone_login', 'user-phone-login', endpoint.user.phone_login, methods=['POST'])
b.add_url_rule('/lit/user/google_login', 'user-google-login', endpoint.user.google_login, methods=['POST'])
b.add_url_rule('/lit/user/facebook_login', 'user-facebook-login', endpoint.user.facebook_login, methods=['POST'])
b.add_url_rule('/lit/user/verify_nickname', 'user-verify-nickname', endpoint.user.verify_nickname)
b.add_url_rule('/lit/user/info', 'user-update-info', endpoint.user.update_info, methods=['POST'])
b.add_url_rule('/lit/user/<target_user_id>', 'user-get-info', endpoint.user.get_user_info)
b.add_url_rule('/lit/user/avatars', 'user-get-avatars', endpoint.user.get_avatars)
b.add_url_rule('/lit/user/info_by_huanxin', 'user-info-by-huanxin', endpoint.user.user_info_by_huanxinids, methods=['POST'])
b.add_url_rule('/lit/user/messages', 'user-messages', endpoint.user.user_messages)
b.add_url_rule('/lit/user/read_message/<message_id>', 'user-message-read', endpoint.user.read_message)
b.add_url_rule('/lit/user/read_all_messages', 'user-read_all_messages', endpoint.user.read_all_messages)
b.add_url_rule('/lit/user/firebase_token', 'user-firebase-token', endpoint.user.register_firebase, methods=['POST'])
b.add_url_rule('/lit/user/firebase_push', 'user-firebase-push', endpoint.user.firebase_push, methods=['POST'])
b.add_url_rule('/lit/user/query_online', 'user-query-online', endpoint.user.query_online, methods=['POST'])
b.add_url_rule('/lit/user/search', 'user-search', endpoint.user.search_user)
b.add_url_rule('/lit/user/accost', 'user-accost', endpoint.user.accost)
b.add_url_rule('/lit/user/accost_other', 'user-accost_other', endpoint.user.accost_other)
b.add_url_rule('/lit/user/conversation', 'user-create-conversation', endpoint.user.add_conversation, methods=['POST'])
b.add_url_rule('/lit/user/pin_conversation', 'user-pin_conversation', endpoint.user.pin_conversation, methods=['POST'])
b.add_url_rule('/lit/user/unpin_conversation', 'user-unpin_conversation', endpoint.user.unpin_conversation, methods=['POST'])
b.add_url_rule('/lit/user/conversations', 'user-conversations', endpoint.user.get_conversations)
b.add_url_rule('/lit/user/del_conversation/<conversation_id>', 'user-del_conversations', endpoint.user.delete_conversation)

# user visit
b.add_url_rule('/lit/user_visit/get_visit_nums', 'user-visit-get_visit_nums', endpoint.user_visit.get_visit_nums)
b.add_url_rule('/lit/user_visit/all_viewed', 'user-visit-all_viewed', endpoint.user_visit.all_viewed)
b.add_url_rule('/lit/user_visit/visited_list', 'user-visit-visited_list', endpoint.user_visit.visited_list)

#  match history
b.add_url_rule('/lit/match_history/matched_history', 'match-history-matched_history', endpoint.match_history.matched_history)
b.add_url_rule('/lit/match_history/send_friend_request', 'match-history-send_friend_request', endpoint.match_history.send_friend_request, methods=['POST'])
b.add_url_rule('/lit/match_history/accept_friend_request', 'match-history-accept_friend_request', endpoint.match_history.accept_friend_request, methods=['POST'])

b.add_url_rule('/lit/account/account_info', 'account-account_info', endpoint.account.account_info)
b.add_url_rule('/lit/account/products', 'account-product_info', endpoint.account.product_info)
b.add_url_rule('/lit/account/pay_activities', 'account-pay_activities', endpoint.account.pay_activities)
b.add_url_rule('/lit/account/pay_inform', 'account-pay_inform', endpoint.account.pay_inform, methods=['POST'])
b.add_url_rule('/lit/account/buy_vip', 'account-buy_vip', endpoint.account.buy_vip, methods=['POST'])
b.add_url_rule('/lit/account/deposit_by_activity', 'account-deposit_by_activity', endpoint.account.deposit_by_activity, methods=['POST'])
b.add_url_rule('/lit/account/buy_product', 'account-buy_product', endpoint.account.buy_product, methods=['POST'])
b.add_url_rule('/lit/account/buy_avatar/<fileid>', 'account-buy_avatar', endpoint.account.buy_avatar)
b.add_url_rule('/lit/account/diamond_products', 'account-diamond_products', endpoint.account.diamond_products)
b.add_url_rule('/lit/account/unban_by_diamonds', 'account-unban-by-diamonds', endpoint.account.unban_by_diamonds)
b.add_url_rule('/lit/account/reset_rate_by_diamonds', 'account-reset_rate_by_diamonds', endpoint.account.reset_rate_by_diamonds, methods=['POST'])
b.add_url_rule('/lit/account/membership_badges', 'account-membership_badges', endpoint.account.membership_badges)


# admin
b.add_url_rule('/lit/admin/index', 'admin-index', endpoint.admin.index)
b.add_url_rule('/lit/admin/admin_feeds', 'admin-admin-feeds', endpoint.admin.feeds_square_html)
b.add_url_rule('/lit/admin/admin_hq', 'admin-admin-hq', endpoint.admin.feeds_hq_html)
b.add_url_rule('/lit/admin/login', 'admin-login', endpoint.admin.login, methods=['POST'])
b.add_url_rule('/lit/admin/hello', 'admin-hello', endpoint.admin.hello)
b.add_url_rule('/lit/admin/query_reports', 'admin-query_reports', endpoint.admin.query_reports)
b.add_url_rule('/lit/admin/ban/<report_id>', 'admin-ban', endpoint.admin.ban_user)
b.add_url_rule('/lit/admin/ban_device/<report_id>', 'admin-ban-device', endpoint.admin.ban_device)
b.add_url_rule('/lit/admin/ban_user_by_feed/<feed_id>', 'admin-ban_by_feed', endpoint.admin.ban_user_by_feed)
b.add_url_rule('/lit/admin/unban', 'admin-unban', endpoint.admin.unban)
b.add_url_rule('/lit/admin/reject/<report_id>', 'admin-reject', endpoint.admin.reject)
b.add_url_rule('/lit/admin/feeds_square', 'admin-feed-square', endpoint.admin.feeds_square_for_admin)
b.add_url_rule('/lit/admin/add_hq/<feed_id>', 'admin-add-hq', endpoint.admin.add_hq)
b.add_url_rule('/lit/admin/remove_from_hq/<feed_id>', 'admin-remove-from-hq', endpoint.admin.remove_from_hq)
b.add_url_rule('/lit/admin/delete_feed/<feed_id>', 'admin-delete-feed', endpoint.admin.delete_feed)
b.add_url_rule('/lit/admin/change_loc', 'admin-change-loc', endpoint.admin.change_loc)
b.add_url_rule('/lit/admin/add_diamonds', 'admin-add_diamonds', endpoint.admin.add_diamonds)
b.add_url_rule('/lit/admin/set_diamonds', 'admin-set_diamonds', endpoint.admin.set_diamonds)
b.add_url_rule('/lit/admin/change_to_official_avatar', 'admin-change_to_official_avatar', endpoint.admin.change_to_official_avatar)
b.add_url_rule('/lit/admin/upload_apk', 'admin-upload_apk', endpoint.admin.upload_apk, methods=['POST'])
b.add_url_rule('/lit/admin/msg_to_region', 'admin-to-region', endpoint.admin.msg_to_region, methods=['POST'])
b.add_url_rule('/lit/admin/send_message', 'admin-send_message', endpoint.admin.send_message_html)
b.add_url_rule('/lit/admin/batch_insert', 'admin-batch_insert', endpoint.admin.batch_insert_html)
b.add_url_rule('/lit/admin/batch_act', 'admin-batch_insert_act', endpoint.admin.batch_act, methods=['POST'])
b.add_url_rule('/lit/admin/load_table_data', 'admin-load_table_data', endpoint.admin.load_table_data, methods=['POST'])
b.add_url_rule('/lit/admin/download_phone', 'admin-download_phone', endpoint.admin.download_phone)
b.add_url_rule('/lit/admin/mail_alert', 'admin-mail-alert', endpoint.admin.mail_alert, methods=['POST'])
b.add_url_rule('/lit/admin/stat_items', 'admin-stat_items', endpoint.admin.stat_items)
b.add_url_rule('/lit/admin/journal', 'admin-journal', endpoint.admin.journal)
b.add_url_rule('/lit/admin/add_stat_item', 'admin-add_stat_item', endpoint.admin.add_stat_item, methods=['POST'])
b.add_url_rule('/lit/admin/delete_stat_item/<item_id>', 'admin-delete_stat_item', endpoint.admin.delete_stat_item)
b.add_url_rule('/lit/admin/get_official_feed', 'admin-get_official_feed', endpoint.admin.get_official_feed)
b.add_url_rule('/lit/admin/add_to_top/<feed_id>', 'admin-add_to_top', endpoint.admin.add_to_top)
b.add_url_rule('/lit/admin/remove_from_top/<feed_id>', 'admin-remove_from_top', endpoint.admin.remove_from_top)
b.add_url_rule('/lit/admin/official_feed', 'admin-official_feed', endpoint.admin.official_feed)
b.add_url_rule('/lit/admin/journal_cal/<item_id>', 'admin-journal_cal', endpoint.admin.journal_cal)
b.add_url_rule('/lit/admin/get_log/<user_id>', 'admin-get_log', endpoint.admin.get_log)
b.add_url_rule('/lit/admin/region_words', 'admin-region_words', endpoint.admin.region_words)
b.add_url_rule('/lit/admin/upsert_region_word', 'admin-upsert_region_word', endpoint.admin.upsert_region_word, methods=['POST'])
b.add_url_rule('/lit/admin/admin_words', 'admin-admin_words', endpoint.admin.admin_words)
b.add_url_rule('/lit/admin/ban_by_uid/<user_id>', 'admin-ban_by_uid', endpoint.admin.ban_by_uid)
b.add_url_rule('/lit/admin/ban_reporter/<user_id>', 'admin-ban_reporter', endpoint.admin.ban_reporter)
b.add_url_rule('/lit/admin/change_setting', 'admin-change_setting', endpoint.admin.change_setting, methods=['POST'])
b.add_url_rule('/lit/admin/mod_setting', 'admin-mod_setting', endpoint.admin.mod_setting)
b.add_url_rule('/lit/admin/mongo_gen_csv', 'admin-mongo_gen_csv', endpoint.admin.mongo_gen_csv)
b.add_url_rule('/lit/admin/mongo_gen_csv_page', 'admin-mongo_gen_csv_page', endpoint.admin.mongo_gen_csv_page)
b.add_url_rule('/lit/admin/feedbacks', 'admin-feedbacks', endpoint.admin.feedbacks)
b.add_url_rule('/lit/admin/deal_feedback/<feedback_id>', 'admin-deal-feedback', endpoint.admin.deal_feedback)
b.add_url_rule('/lit/admin/feedback_page', 'admin-feedback_page', endpoint.admin.feedback_page)
b.add_url_rule('/lit/admin/unban_by_nickname', 'admin-unban_by_nickname', endpoint.admin.unban_by_nickname)
b.add_url_rule('/lit/admin/unban_by_user_id/<user_id>', 'admin-unban_by_user_id', endpoint.admin.unban_by_user_id)
b.add_url_rule('/lit/admin/release_vip', 'admin-release_vip', endpoint.admin.release_vip)
b.add_url_rule('/lit/admin/restart_test', 'admin-restart_test', endpoint.admin.restart_test)
b.add_url_rule('/lit/admin/set_exp', 'admin-set_exp', endpoint.admin.set_exp)
b.add_url_rule('/lit/admin/agent', 'admin-agent', endpoint.admin.agent, methods=['POST'])
b.add_url_rule('/lit/admin/replace_image', 'admin-replace_image', endpoint.admin.replace_image, methods=['POST'])
b.add_url_rule('/lit/admin/forbid_score','admin-forbid_score',endpoint.admin.forbid_score)
b.add_url_rule('/lit/admin/judge_pic','admin-judge_pic',endpoint.admin.judge_pic,methods=['POST'])
b.add_url_rule('/lit/admin/judge_lit_pic','admin-judge_lit_pic',endpoint.admin.judge_lit_pic,methods=['POST'])
b.add_url_rule('/lit/admin/test_to_delete_users','admin-test_to_delete_users', endpoint.admin.test_to_delete_users)
b.add_url_rule('/lit/admin/test_delete_old_users','admin-test_delete_old_users',endpoint.admin.test_delete_old_users)
b.add_url_rule('/lit/admin/get_feed', 'admin-get_feed', endpoint.admin.get_feed)
b.add_url_rule('/lit/admin/review_record', 'admin-review_record', endpoint.admin.review_record)
b.add_url_rule('/lit/admin/review_feed', 'admin-review_feed', endpoint.admin.review_feed)
b.add_url_rule('/lit/admin/review_report', 'admin-review_report', endpoint.admin.review_report)
b.add_url_rule('/lit/admin/review_forbid_record', 'admin-review_forbid_record', endpoint.admin.review_forbid_record)
b.add_url_rule('/lit/admin/resolve_review_record', 'admin-resolve_review_record', endpoint.admin.resolve_review_record)
b.add_url_rule('/lit/admin/resolve_review_feed', 'admin-resolve_review_feed', endpoint.admin.resolve_review_feed)
b.add_url_rule('/lit/admin/super_login', 'admin-super_login', endpoint.admin.super_login, methods=['POST'])
b.add_url_rule('/lit/admin/huanxin_by_uid', 'admin-huanxin_by_uid', endpoint.admin.huanxin_by_uid)
b.add_url_rule('/lit/admin/sync_region_to_online', 'admin-sync_region_to_online', endpoint.admin.sync_region_to_online)
b.add_url_rule('/lit/admin/user/<user_id>', 'admin-get_user_info', endpoint.admin.get_user_info)


# picture
b.add_url_rule('/lit/image/upload', 'image-upload', endpoint.oss.upload_image_from_file, methods=['POST'])
b.add_url_rule('/lit/image/chat_upload', 'image-upload', endpoint.oss.upload_image_from_file, methods=['POST'])
# b.add_url_rule('/lit/image/<fileid>', 'get-image', endpoint.oss.get_image)
b.add_url_rule('/lit/image/<fileid>', 'get-image', endpoint.oss.get_image)
b.add_url_rule('/lit/simage/<fileid>', 'get-simage', endpoint.oss.get_simage)
b.add_url_rule('/lit/gimage/<fileid>', 'get-gimage', endpoint.oss.get_gimage)
b.add_url_rule('/lit/audio/upload', 'audio-upload', endpoint.oss.upload_audio_from_file, methods=['POST'])
b.add_url_rule('/lit/audio/<fileid>', 'get-audio', endpoint.oss.get_audio)
b.add_url_rule('/lit/log/upload', 'log-upload', endpoint.oss.upload_log_from_file, methods=['POST'])
b.add_url_rule('/lit/log/upload_from_device', 'log-upload_from_device', endpoint.oss.upload_log_from_device, methods=['POST'])
b.add_url_rule('/lit/log/<fileid>', 'get-log', endpoint.oss.get_log)
b.add_url_rule('/lit/mp3audio/<fileid>', 'get-mp3audio', endpoint.oss.get_audio_mp3)

# home
b.add_url_rule('/lit/home/online_user_count', 'home-online-user-count', endpoint.home.online_user_count)
b.add_url_rule('/lit/home/online_users', 'home-online-users', endpoint.home.online_users)
b.add_url_rule('/lit/home/wording', 'home-wordings', endpoint.home.get_wording)
b.add_url_rule('/lit/home/report', 'home-report', endpoint.home.report, methods=['POST'])
b.add_url_rule('/lit/home/report/<report_id>', 'home-report-info', endpoint.home.report_info)
b.add_url_rule('/lit/home/feedback', 'home-feedback', endpoint.home.feedback, methods=['POST'])
b.add_url_rule('/lit/home/feedback/<feedback_id>', 'home-feedback-info', endpoint.home.feedback_info)
b.add_url_rule('/lit/home/track', 'home-track-chat', endpoint.home.track_chat, methods=['POST'])
b.add_url_rule('/lit/home/track_action', 'home-track-action', endpoint.home.track_action, methods=['POST'])
b.add_url_rule('/lit/home/track_network', 'home-track-network', endpoint.home.track_network, methods=['POST'])
b.add_url_rule('/lit/home/track_action', 'home-action-info', endpoint.home.action_by_user_id)
b.add_url_rule('/lit/home/privacy', 'home-privacy', endpoint.home.privacy)
b.add_url_rule('/lit/home/rules', 'home-rules', endpoint.home.rules)
b.add_url_rule('/lit/home/community_rule', 'home-community_rule', endpoint.home.community_rule)
b.add_url_rule('/lit/home/community_guidelines', 'home-community_guidelines', endpoint.home.community_guidelines)
b.add_url_rule('/lit/home/index', 'home-index', endpoint.home.index)
b.add_url_rule('/lit/home/check_version', 'home-check-version', endpoint.home.check_version)
b.add_url_rule('/lit/home/settings', 'home-setting', endpoint.home.settings)
b.add_url_rule('/lit/home/user_filters', 'home-user-filter', endpoint.home.online_filter, methods=['POST'])
b.add_url_rule('/lit/home/first_start', 'home-first-start', endpoint.home.first_start)
b.add_url_rule('/lit/home/get_filters', 'home-get-filter', endpoint.home.get_online_filter)
b.add_url_rule('/lit/home/download', 'home-download', endpoint.home.download_app)
b.add_url_rule('/lit/home/upload_address_list', 'home-upload_address_list', endpoint.home.upload_address_list, methods=['POST'])
b.add_url_rule('/lit/home/address_list', 'home-get_address_list', endpoint.home.get_address_list)
b.add_url_rule('/lit/home/spam_words', 'home-spam_words', endpoint.home.get_spam_word)
b.add_url_rule('/lit/home/report_spam', 'home-report_spam', endpoint.home.report_spam, methods=['POST'])
b.add_url_rule('/lit/home/check_pic', 'home-check_pic', endpoint.home.check_pic, methods=['POST'])
b.add_url_rule('/lit/home/experiments', 'home-experiments', endpoint.home.experiments)
b.add_url_rule('/lit/home/report_acted', 'home-report_acted', endpoint.home.report_acted, methods=['POST'])
b.add_url_rule('/lit/home/acted_actions', 'home-acted_actions', endpoint.home.acted_actions)

# huanxin
b.add_url_rule('/lit/huanxin/<target_user_id>', 'huanxin-get-info', endpoint.huanxin.get_user_info)

# activity
b.add_url_rule('/lit/activity/palm/query', 'activity-palm-query', endpoint.activity.palm_query)
b.add_url_rule('/lit/activity/palm/share', 'activity-palm-share', endpoint.activity.share_info)
b.add_url_rule('/lit/activity/palm/times_left', 'activity-palm-times-left', endpoint.activity.times_left)
b.add_url_rule('/lit/activity/user_share/<share_user_id>', 'activity-user-share', endpoint.activity.user_share)
b.add_url_rule('/lit/activity/share_static1', 'activity-share-static', endpoint.activity.share_static)
b.add_url_rule('/lit/activity/claim_rewards', 'activity-claim-rewards', endpoint.activity.claim_rewards)
b.add_url_rule('/lit/activity/share_num', 'activity-share-num',endpoint.activity.share_num)
b.add_url_rule('/lit/activity/admin', 'activity-adnmin', endpoint.activity.admin_page)

# anoy_match
b.add_url_rule('/lit/anoy_match/get_fakeid', 'anoy-match-create-fakeid', endpoint.anoy_match.get_fakeid)
b.add_url_rule('/lit/anoy_match/anoy_match', 'anoy-match-anoy-match', endpoint.anoy_match.anoy_match)
b.add_url_rule('/lit/anoy_match/anoy_like', 'anoy-match-anoy-like', endpoint.anoy_match.anoy_like)
b.add_url_rule('/lit/anoy_match/quit_match', 'anoy-match-quit-match', endpoint.anoy_match.quit_match)
b.add_url_rule('/lit/anoy_match/times_left', 'anoy-match-times-left', endpoint.anoy_match.match_times_left)
b.add_url_rule('/lit/anoy_match/tips', 'anoy-match-tips', endpoint.anoy_match.get_tips)
b.add_url_rule('/lit/anoy_match/judge', 'anoy-match-judge', endpoint.anoy_match.anoy_judge, methods=['POST'])
b.add_url_rule('/lit/anoy_match/video_list', 'anoy-match-video-list', endpoint.anoy_match.video_list)
b.add_url_rule('/lit/anoy_match/video_info_list', 'anoy-match-video-info-list', endpoint.anoy_match.video_info_list)
b.add_url_rule('/lit/anoy_match/video/<vid>', 'anoy-match-update-video', endpoint.anoy_match.update_video, methods=['POST'])
b.add_url_rule('/lit/anoy_match/add_time_by_ad', 'anoy-match-add-time-by-ad', endpoint.anoy_match.add_time_by_ad, methods=['POST'])
b.add_url_rule('/lit/anoy_match/accelerate_by_ad', 'anoy-match-accelerate-by-ad', endpoint.anoy_match.accelerate_by_ad, methods=['POST'])
b.add_url_rule('/lit/anoy_match/accelerate_info', 'anoy-match-accelerate-info', endpoint.anoy_match.get_accelerate_info)

# experiments
b.add_url_rule('/lit/experiment/set_experiments', 'experiment-set_experiments', endpoint.experiment.set_experiments, methods=['POST'])
b.add_url_rule('/lit/experiment/get_experiments', 'experiment-get_experiments', endpoint.experiment.get_experiments)
b.add_url_rule('/lit/experiment/get_exp_value', 'experiment-get_exp_value', endpoint.experiment.get_exp_value)
b.add_url_rule('/lit/experiment/all_experiments', 'experiment-all_experiments', endpoint.experiment.get_all_experiments)
b.add_url_rule('/lit/experiment/delete_experiment', 'experiment-delete_experiment', endpoint.experiment.delete_experiment)

# debug
b.add_url_rule('/lit/debug/redis_status', 'debug-redis-status', endpoint.debug.redis_status)
b.add_url_rule('/lit/debug/clear_redis', 'debug-clear-redis', endpoint.debug.clear_keys)
b.add_url_rule('/lit/debug/batch_create_login', 'debug-batch-create-login', endpoint.debug.batch_create_login)
b.add_url_rule('/lit/debug/batch_anoy_match_start', 'debug-batch-anoy-match-start', endpoint.debug.batch_anoy_match_start)
b.add_url_rule('/lit/debug/query_region', 'debug-query-region', endpoint.debug.query_region)
b.add_url_rule('/lit/debug/test_func', 'debug-test_func', endpoint.debug.test_func)
b.add_url_rule('/lit/debug/chat_msg', 'debug-chat-msg', endpoint.debug.chat_msg)
b.add_url_rule('/lit/debug/user_info', 'debug-user_info', endpoint.debug.user_info)
b.add_url_rule('/lit/debug/register_yesterday', 'debug-register_yesterday', endpoint.debug.change_register_to_yes)
b.add_url_rule('/lit/debug/delete_matched_record', 'debug-del_match_before', endpoint.debug.del_match_before)
b.add_url_rule('/lit/debug/delete_online_matched_record', 'debug-online_del_match_status', endpoint.debug.online_del_match_status)
b.add_url_rule('/lit/debug/set_times_to1', 'debug-set-times-to1', endpoint.debug.set_left_times_to_1)
b.add_url_rule('/lit/debug/down_log/<user_id>', 'debug-down_log', endpoint.debug.down_log)


# feed
b.add_url_rule('/lit/feed/create', 'feed-create-feed', endpoint.feed.create_feed, methods=['POST'])
b.add_url_rule('/lit/feed/view/<other_user_id>', 'feed-user-feeds', endpoint.feed.user_feeds)
b.add_url_rule('/lit/feed/following_feeds', 'feed-following-feeds', endpoint.feed.user_following_feeds)
b.add_url_rule('/lit/feed/square', 'feed-square-feeds', endpoint.feed.square_feeds)
b.add_url_rule('/lit/feed/hq', 'feed-hq-feeds', endpoint.feed.hq_feeds)
b.add_url_rule('/lit/feed/like/<feed_id>', 'feed-like-feed', endpoint.feed.like_feed)
b.add_url_rule('/lit/feed/dislike/<feed_id>', 'feed-dislike-feed', endpoint.feed.dislike_feed)
b.add_url_rule('/lit/feed/delete/<feed_id>', 'feed-delete-feed', endpoint.feed.delete_feed)
b.add_url_rule('/lit/feed/comment/<feed_id>', 'feed-comment-feed', endpoint.feed.comment_feed, methods=['POST'])
b.add_url_rule('/lit/feed/del_comment/<comment_id>', 'feed-comment-delete', endpoint.feed.del_comment)
b.add_url_rule('/lit/feed/comment/<feed_id>', 'feed-feed-comments', endpoint.feed.feed_comments)
b.add_url_rule('/lit/feed/info/<feed_id>', 'feed-feed-info', endpoint.feed.feed_info)
b.add_url_rule('/lit/feed/pin_feed/<feed_id>', 'feed-pin_feed', endpoint.feed.pin_feed)
b.add_url_rule('/lit/feed/unpin_feed/<feed_id>', 'feed-unpin_feed', endpoint.feed.unpin_feed)

# user_relations
b.add_url_rule('/lit/block/<other_user_id>', 'block', endpoint.user_relations.block)
b.add_url_rule('/lit/unblock/<other_user_id>', 'unblock', endpoint.user_relations.unblock)
b.add_url_rule('/lit/blocks', 'blocks', endpoint.user_relations.blocks)
b.add_url_rule('/lit/follow/<other_user_id>', 'follow', endpoint.user_relations.follow)
b.add_url_rule('/lit/unfollow/<other_user_id>', 'unfollow', endpoint.user_relations.unfollow)
b.add_url_rule('/lit/following', 'following', endpoint.user_relations.following)
b.add_url_rule('/lit/follower', 'follower', endpoint.user_relations.follower)

b.add_url_rule('/lit/ad/times_left', 'ad-times-left', endpoint.ad.times_left)
b.add_url_rule('/lit/ad/reset_accost', 'ad-reset_accost', endpoint.ad.reset_accost, methods=['POST'])

# voice_chat
# b.add_url_rule('/lit/voice_chat/invite/<target_user_id>', 'voice_chat-invite', endpoint.voice_chat.invite)
# b.add_url_rule('/lit/voice_chat/finish', 'finish_chat', endpoint.voice_chat.finish_chat)
# b.add_url_rule('/lit/voice_chat/accept/<target_user_id>', 'voice_chat-accept', endpoint.voice_chat.accept)
# b.add_url_rule('/lit/voice_chat/cancel', 'cancel_chat', endpoint.voice_chat.cancel)
# b.add_url_rule('/lit/voice_chat/reject/<target_user_id>', 'voice_chat-reject', endpoint.voice_chat.reject)
b.add_url_rule('/lit/voice_chat/room_id', 'voice_get_roomid', endpoint.voice_chat.get_roomid, methods=['POST'])
